title: Data science portfolio par Matieu Allier
description: Portfolio réalisé à partir de github et de Jekyll Theme. [Link](https://medium.com/@HarryWang/how-to-host-static-markdown-web-pages-using-github-pages-61f80a3a5136)
google_analytics:
theme: jekyll-theme-slate
